Update article page
spryker/spryker.github.io pull request #106
Opened 2021-06-15 09:59 UTC by skliarzfort

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-06-18 10:16 UTC, tolerants requested changes

2021-06-18 12:05 UTC, skliarzfort commented on css/components/_related-links.scss
> +        &, .post-content & {
to override .post-content h2

2021-06-18 12:10 UTC, skliarzfort commented on js/algolia-search.js
> +            const renderPagination = (renderOptions, isFirstRender) => {
removed

2021-06-18 12:39 UTC, skliarzfort commented on js/algolia-search.js
> +            const renderPagination = (renderOptions, isFirstRender) => {
yeap)

2021-06-22 09:48 UTC, tolerants approved these changes

2021-06-22 09:48 UTC, merged