Update nav accordeon
spryker/spryker.github.io pull request #108
Opened 2021-06-16 16:50 UTC by skliarzfort

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-06-23 06:16 UTC, tolerants requested changes

2021-06-23 08:35 UTC, skliarzfort commented on css/pages/_content.scss
> +    width: calc(100% - 655px);
width of 2 sidebars

2021-06-25 09:51 UTC, tolerants commented on css/pages/_content.scss
> +    width: calc(100% - 655px);
Suggest to move it into the variable so another developer will be able to understand where this number is coming from.

2021-07-02 07:34 UTC, tolerants approved these changes

2021-07-05 08:09 UTC, merged