Responsive home
spryker/spryker.github.io pull request #109
Opened 2021-06-22 10:45 UTC by skliarzfort

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-06-23 08:08 UTC, tolerants requested changes

2021-06-25 09:56 UTC, tolerants commented on css/base/_include-media.scss
> +@charset 'UTF-8';
The question was about this whole file.

2021-07-01 13:52 UTC, skliarzfort commented on css/base/_include-media.scss
> +@charset 'UTF-8';
Let's leave it as it is. we can't add Node.js to build

2021-07-02 07:35 UTC, tolerants approved these changes

2021-07-05 13:35 UTC, merged