[WIP] API: Offers Volume Prices [MP-3971]
spryker/spryker.github.io pull request #160
Opened 2021-07-16 16:09 UTC by lenadoc

## PR Description

TBD

## Checklist
- [ ] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

2021-07-21 20:17 UTC, asmarovydlo requested changes

2021-07-21 20:17 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/guest-carts/managing-guest-cart-items.md
> +* [Glue API: Marketplace Product Offer Volume Prices feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/glue-api-marketplace-product-offer-volume-prices.htm
There is no product volume prices example, do we really need it here?
(But we have an example with `Marketplace Product Offer`, link should be added)

2021-07-21 20:17 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/carts-of-registered-users/managing-items-in-carts-of-registered-users.md
> +* * [GLUE API: Merchant Offers feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/marketplace-product-offer-feature-integration.html)
```suggestion
* [GLUE API: Merchant Offers feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/marketplace-product-offer-feature-integration.html)
```

2021-07-21 20:17 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/carts-of-registered-users/managing-carts-of-registered-users.md
> +| `GET http://glue.mysprykershop.com/carts?include=items,concrete-products,product-offers,product-offer-availabilities,product-offer-prices` | Retrieve all carts of a user with product offer availabi
Example with prices is the next one.
```suggestion
| `GET http://glue.mysprykershop.com/carts?include=items,concrete-products,product-offers,product-offer-availabilities` | Retrieve all carts of a user with product offer availabilities. |
```

2021-07-21 20:17 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/carts-of-registered-users/managing-carts-of-registered-users.md
> +<summary markdown='span'>Response sample with product offers</summary>
I would exclude not relative things from the response (E.g. here `concrete-products` can be removed from the request `include` parameter), output is too big.

2021-08-03 07:21 UTC, andriitserkovnyi requested changes

2021-08-03 09:53 UTC, lenadoc commented on docs/marketplace/dev/glue-api-guides/202106.0/carts-of-registered-users/managing-carts-of-registered-users.md
> +| `GET https://glue.mysprykershop.com/carts?include=items,concrete-products,product-offers` | Retrieve all carts of a user with information about product offers. |
items and concrete products are needed to retrieve product offers, product offer availabilities, and product offer prices, we have this in the info block above: 
```
* To retrieve product offers, include `items` and `concrete-products`.
* To retrieve product offer availabilities, include `items`, `concrete-products`, and `product-offer-availabilities`.
* To retrieve product offer prices, include `items`, `concrete-products`, and `product-offer-prices`.
```

2021-08-03 10:27 UTC, lenadoc commented on docs/marketplace/dev/glue-api-guides/202106.0/guest-carts/managing-guest-carts.md
> +| `GET https://glue.mysprykershop.com/guest-carts?include=items,concrete-products,product-offers` | Retrieve all guest carts of a user with information about product offers. |
this might not be obvious and could be interpreted like "retrieve all guest carts available in the system"

2021-08-04 11:14 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/concrete-products/retrieving-concrete-products.md
> +* [GLUE API: Merchant Offers feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/marketplace-product-offer-feature-integration.html)
```suggestion
* [GLUE API: Marketplace Product Offer feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/marketplace-product-offer-feature-integration.html)
```

2021-08-04 11:17 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/retrieving-product-offers.md
> +* [GLUE API: Merchant Offers feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/marketplace-product-offer-feature-integration.html)
```suggestion
* [GLUE API: Marketplace Product Offer feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/marketplace-product-offer-feature-integration.html)
```

2021-08-04 11:22 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/guest-carts/managing-guest-cart-items.md
> +                "self": "https://glue.mysprykershop.com:80/guest-carts/6851dc6a-ebed-52ed-b229-81a35fe94c49/guest-cart-items/041_25904691_offer48"
```suggestion
                "self": "https://glue.mysprykershop.com/guest-carts/6851dc6a-ebed-52ed-b229-81a35fe94c49/guest-cart-items/041_25904691_offer48"
```

2021-08-04 11:22 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/guest-carts/managing-guest-cart-items.md
> +            "self": "https://glue.mysprykershop.com:80/guest-carts/6851dc6a-ebed-52ed-b229-81a35fe94c49"
```suggestion
            "self": "https://glue.mysprykershop.com/guest-carts/6851dc6a-ebed-52ed-b229-81a35fe94c49"
```

2021-08-04 11:36 UTC, asmarovydlo commented on docs/marketplace/dev/glue-api-guides/202106.0/guest-carts/managing-guest-carts.md
> +* [GLUE API: Merchant Offers feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/marketplace-product-offer-feature-integration.html)
```suggestion
* [GLUE API: Marketplace Poruduct Offer feature integration](/docs/marketplace/dev/feature-integration-guides/{{ page.version }}/glue/marketplace-product-offer-feature-integration.html)
```

2021-08-04 15:24 UTC, merged